name: Deploy - Production - Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
    name: 'Deploy - Production - Website'

  repository_dispatch:
    types:
      - webhook

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  GTM_ID: ${{ secrets.GTM_ID }}

jobs:
  deploy-production-website:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://www.colabra.ai'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: 'Build And Deploy Website'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEB_STATIC_SITE_SECRET }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist'
          app_build_command: 'yarn generate'
